/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,html}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#ffff",
        secondary: "#f0f2f5",
        third: "#e4e6eb",
        forth: "#f0f2f5",
        "color-primary": "#050505",
        "color-secondary": "#65676b",
        "divider-color": "#ced0d4",
        "dark-primary": "#18191a",
        "dark-secondary": "#242526",
        "dark-third": "#3a3b3c",
        "dark-forth": "#4E4F50",
        "dark-color-primary": "#f0f2f5",
        "dark-color-secondary": "#b0b3b8",
        "blue-color": "#1876f2",
        "medium-blue": "#263951",
        "green-color": "#42b72a",
        "light-blue-color": "#e7f3ff",
        "border-color": "#ccced2",
        "shadow-one": "rgba(0, 0, 0, 0.2)",
        "shadow-two": "rgba(0, 0, 0, 0.1)",
        "shadow-three": "rgba(0, 0, 0, 0.3)",
        "shadow-inset": "rgba(255, 255, 255, 0.5)",
        neutral: "#3D4451",
        info: "#3ABFF8",
        success: "#36D399",
        warning: "#FBBD23",
        error: "#F87272",
      },
    },
  },
  plugins: [],
};
